### ISSUE TITLE
--remove $GOPATH

### ISSUE THREAD

**Issue by HamzaAnis** [canha/golang-tools-install-script#15]
When removing the Go, shouldn't the script handle the $GOPATH and remove it automatically which would be $HOME/go because in the current script when we reinstall it asks to delete $GOPATH manually?

**Comment by kerolloz** [comment]
@HamzaAnis 
please check my [repo](/kerolloz/go-installer), I fixed this issue.

**Comment by canha** [comment]
Sorry it took so long to respond. This was just forgotten.

This was originally intended so that you wouldn't lose data - but in reality we don't need to block the install just because `$HOME/go` exists, only the `.go` folder. I'll create a new commit to address this, thanks for pointing it out.

![](https://media2.giphy.com/media/oGO1MPNUVbbk4/giphy.gif)
