### ISSUE TITLE
Can't show go version

### ISSUE THREAD

**Issue by abhishekcse134** [canha/golang-tools-install-script#6]
Hi ,canha
  i run your script to setup go in my ubuntu machine . i'm just trying to check go version from konsole 
 but it showing command not found and how can i run my first program in go please help me regrading this

**Comment by canha** [comment]
Hello!

Assuming you are using bash, which is the only shell being at the present:

That might be because the ~/.bashrc is not being loaded by the terminal/your profile, therefore it can't find the binary.

You can try adding the export commands (lines 51 to 55) to ~/.bash_profile if it exists. If that doesn't work, then Konsole might not be actually "logging" you in when you open a new tab (there's an option that you can toggle for that in the preferences I believe) or simply that your system isn't reading the bash configuration files from your home directory. Tell me how it goes.

**Comment by canha** [comment]
Closing this as it's been a while with no feedback. Feel free to reopen if need be.
